# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='default.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
